### ISSUE TITLE
Project specifications 

### ISSUE THREAD

**Issue by DocAmaroo** [GraciaMoulisKevin/Thovin#53]
:pushpin: **Client**
---
- [x] Authentication (login/register/logout)
- [x] Ajout au panier (issue #50)
- [ ] Supprimer un élément du panier (issue #50)
- [x] Supprimer tout les items du panier (issue #50) 
- [x] Paiement
- [x] Historique et commande en cours (issue #60)
- [x] Filtrer les restaurants par catégorie
- [ ] Ajout des extras
- [ ] Mode guest

:pushpin: **Deliverer**
---
- [x] Authentication (login/register/logout)
- [x] Historique et livraison en cours (issue #61)
- [x] Mettre à jour l'état d'une commande
- [x] Notification/Vibration de nouvelle commande
- [ ] Utiliser le status pour activer/désactiver les notifs

:pushpin: **Restauranteur**
---
- [x] Authentication (login/register/logout)
- [x] Ajout d'un nouveau produit (issue #55)
- [ ] Ajout d'un nouveau menu
- [x] Supprimer un produit (issue #55)
- [ ] Supprimer un menu
